services:
  spring-blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-blue
    ports:
      - "8081:8080"
    networks:
      - app

  spring-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-green
    ports:
      - "8082:8080"
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - spring-blue
      - spring-green
    networks:
      - app

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app

volumes:
  jenkins_home:

networks:
  app: